// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOr6ccmW1X_ZewLKAJLL0XuEwzQCZxHbA',
    appId: '1:400545822046:web:2b8af86566c2e319cd4bcf',
    messagingSenderId: '400545822046',
    projectId: 'facialrecognition-9ffcb',
    authDomain: 'facialrecognition-9ffcb.firebaseapp.com',
    storageBucket: 'facialrecognition-9ffcb.firebasestorage.app',
    measurementId: 'G-K0D145GQF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASa0f-mGbdUU8VEgnsGvLIWvM-8DbVgts',
    appId: '1:400545822046:android:c00e204a17bfb870cd4bcf',
    messagingSenderId: '400545822046',
    projectId: 'facialrecognition-9ffcb',
    storageBucket: 'facialrecognition-9ffcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGZGkUGX97e1niGdkmltQCIh-coQXXWro',
    appId: '1:400545822046:ios:9badeae0b89db517cd4bcf',
    messagingSenderId: '400545822046',
    projectId: 'facialrecognition-9ffcb',
    storageBucket: 'facialrecognition-9ffcb.firebasestorage.app',
    iosBundleId: 'com.example.appLina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGZGkUGX97e1niGdkmltQCIh-coQXXWro',
    appId: '1:400545822046:ios:9badeae0b89db517cd4bcf',
    messagingSenderId: '400545822046',
    projectId: 'facialrecognition-9ffcb',
    storageBucket: 'facialrecognition-9ffcb.firebasestorage.app',
    iosBundleId: 'com.example.appLina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOr6ccmW1X_ZewLKAJLL0XuEwzQCZxHbA',
    appId: '1:400545822046:web:4c7a8aea1c967c7fcd4bcf',
    messagingSenderId: '400545822046',
    projectId: 'facialrecognition-9ffcb',
    authDomain: 'facialrecognition-9ffcb.firebaseapp.com',
    storageBucket: 'facialrecognition-9ffcb.firebasestorage.app',
    measurementId: 'G-HDY8WMK2LY',
  );

}